[package]
name = "deployer"
version = "0.1.0"
edition = "2018"


[dependencies]
anyhow = "1"
reqwest = { version = "0.11", features = ["native-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }