[package]
name = "deployer"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
async-recursion = "0.3"
bytes = "1"
git2 = "0.13"
hex = "0.4"
reqwest = { version = "0.11", features = ["native-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }