
name: Deploy latest build

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build from main"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    container: rfkelly/website-tooling:latest
    steps:
      - uses: actions/checkout@v2

      - name: Checks
        run: |
          ls

      - name: Deploy it
        run: deployer
