
name: Deploy latest build

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build from main"]
    types:
      - completed

env:
  WEBDAV_BASE_URL: "https://webdav.fastmail.com/rfkelly.fastmail.fm/files/www.rfk.id.au/"
  WEBDAV_USERNAME: ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    container: rfkelly/website-tooling:latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          git remote set-branches --add origin built
          git fetch origin built
          git checkout -t origin/built

      - name: Deploy
        run: deployer
